@Controller.API_HostAddress = http://localhost:5172

GET {{Controller.API_HostAddress}}/api/hello
Accept: application/json

###

GET {{Controller.API_HostAddress}}/api/hello/Alex
Accept: application/json